#pragma once

#include <random>

#include "dla_graph.hh"
#include "heightmap.hh"

namespace DLA {

// TODO: Experiment with generator hyperparameters to get different results
class DLAGenerator // Diffusion Limited Aggregation
{
private:
    std::random_device rd_;
    std::mt19937 rng_;

    static std::uniform_real_distribution<float> real_dist_1_;
    static std::uniform_real_distribution<float> real_dist_1_zero_centered_;
    static std::uniform_real_distribution<float> real_dist_2pi_;

public:
    float density_threshold_; // grid density required to stop populating the grid
    float graph_center_y_; // y ratio of the graph center (also first node) (0 < y < 1) (will be scaled to the current grid)
    float graph_center_x_; // x ratio of the graph center (also first node) (0 < x < 1) (will be scaled to the current grid)

    DLAGenerator();
    DLAGenerator(float density_threshold);
    DLAGenerator(float density_threshold, int seed); // use fixed seed to get reproducible results
    DLAGenerator(float density_threshold, float first_node_y, float first_node_x, int seed);

    std::array<float, 2> getRandom2DPixelCoordinates(int width, int height); // no real need to put it here but needs random engine class attribute
    void populateGraph(int width, Graph& graph);

    void upscaleGraph(Graph& graph);
    Heightmap upscaleBlurryGrid(const Heightmap& low_res_blurry_grid);

    void setGraphHeightValues(Graph& graph);
    Heightmap graphToHeightmap(int width, const Graph& graph);

    /**
     * @brief Generate (square) heightmap using DLA algorithm
     *
     * @param[in] width  width of the final square heightmap (needs to be a power of 2 (>= 2^4))
     *
     * @return square heightmap representing some terrain (mountains)
     */
    Heightmap generateUpscaledHeightmap(int width);

    /**
     * @brief Generate the base heightmap (for the mesh) and the upscaled heightmap (for the texture map and the normal map).
     * The upscaled heightmap will be generated by the DLA algorithm. Base heightmap is a downsampled version of the upscaled heightmap.
     *
     * @param[out] base_heightmap      base heightmap (for the mesh), width must be a power of 2.
     * @param[out] upscaled_heightmap  upscaled heightmap (for the texture map and the normal map), width must be a power of 2 (>= 2^4).
     */
    void generateHeightmaps(Heightmap& base_heightmap, Heightmap& upscaled_heightmap);
};

} // namespace DLA